# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "python:3.7"

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
      set -e

      # Our build hook uses `dash` rather than `bash`. dash is missing an important
      # feature that is necessary for the `conda activate` command to run, so we
      # must write the build hook in a separate script that runs with `bash`.

      # NOTE: If a user connects to the container using `platform ssh`, they'll be
      # given a bash shell, so all commands will run normally.

      # See the contents of `install_r.sh` for the rest of the build hook.

      bash install_r.sh

    deploy: |
      set -e

      # Make the start script executable
      chmod +x start_command.sh

# The size of the persistent disk of the application (in MB).
disk: 2048

# The configuration of app when it is exposed to the web.
web:
    commands:
        # start: bash ./start_command.sh
        start: sleep infinity
    upstream:
        socket_family: tcp
        protocol: http
    locations:
        "/":
            passthru: true

variables:
    env:
        PORT: 8888
